name: Deploy Documentation
run-name: ${{ github.actor }} is trying to deploy documentation 🚀
on:
  pull_request:
  workflow_dispatch:

jobs:
  deploy_docs:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
#      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action
      - run: echo "The docs will are uploaded to ${{steps.deployment.outputs.page_url}}."
